### ISSUE TITLE
torch.manual_seed return is not assigned to a variable?

### ISSUE THREAD

**Issue by bghira** [Birch-san/sdxl-play#1]
Howdy, checking through your implementation with Diffusers and I noticed you're setting manual_seed but the returned torch.Generator isn't assigned to a value or passed into the refiner.

**Comment by Birch-san** [comment]
could you please tell me which file + line of code?

**Comment by bghira** [comment]
https://github.com/Birch-san/sdxl-play/blob/main/scripts/sdxl_diffusers_play.py#L139

**Comment by Birch-san** [comment]
that API call seeds the RNG for all devices in torch. it works due to side-effects. it’s not necessary to use the Generator it returns.

https://pytorch.org/docs/stable/notes/randomness.html#pytorch-random-number-generator
